name: Build ESharp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.15.0'

    - name: Configure (Unix)
      if: matrix.os != 'windows-latest'
      run: cmake -B build -S .

    - name: Configure (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -B build -S . -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build
